#!/bin/bash

# This is a thin wrapper around litecoinz-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using litecoinz-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_LITECOINZD

# Grab the value of $REAL_LITECOINZCLI which may be litecoinz-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_LITECOINZCLI}" "$@" | sed 's/\r//'
